version: '3.8'

services:
  android-builder:
    build: .
    volumes:
      - ./output:/output
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
    command: >
      sh -c "
        ./gradlew assembleRelease &&
        cp app/build/outputs/apk/release/app-release.apk /output/ &&
        echo 'APK build completed successfully!'
      "